/* eslint-disable react/jsx-closing-bracket-location */
/* eslint-disable react/jsx-indent-props */
/* eslint-disable react/jsx-tag-spacing */
/* eslint-disable react/jsx-no-bind */
/* eslint-disable no-trailing-spaces */
/* eslint-disable no-console */
/* eslint-disable comma-dangle */
/* eslint-disable import/named */
/* eslint-disable react/jsx-no-undef */
/* eslint-disable no-shadow */
/* eslint-disable camelcase */
import React, { useState } from 'react';
import { Table, Typography } from 'antd';

const { Title } = Typography;

export function GPUhashrate() {
    // eslint-disable-next-line no-undef
    // eslint-disable-next-line camelcase
    const [ETH_Hashrate] = useState([
        {
            id: 1,
            GPUname: 'NVIDIA RTX 3090',
            Hashrate: '124.09  ',
            Power: '294',
            Efficency: '0.42',
            Revenue: '4.10',
            ROI: '366',
        },
        {
            id: 2,
            GPUname: 'AMD VII',
            Hashrate: '108.50  ',
            Power: '236',
            Efficency: '0.46',
            Revenue: '3.58',
            ROI: '195',
        },
        {
            id: 3,
            GPUname: 'NVIDIA RTX A5000',
            Hashrate: '101.78  ',
            Power: '215',
            Efficency: '0.47',
            Revenue: '3.36',
            ROI: '670',
        },
        {
            id: 4,
            GPUname: 'NVIDIA RTX 3080',
            Hashrate: '101.58  ',
            Power: '224',
            Efficency: '0.45',
            Revenue: '3.35',
            ROI: '208',
        },
        {
            id: 5,
            GPUname: 'NVIDIA CMP 90HX',
            Hashrate: '100.16  ',
            Power: '249',
            Efficency: '0.40',
            Revenue: '3.31',
            ROI: '484',
        },
        {
            id: 6,
            GPUname: 'NVIDIA RTX A4500',
            Hashrate: '87.00  ',
            Power: '178',
            Efficency: '0.49',
            Revenue: '2.87',
            ROI: '870',
        },
        {
            id: 7,
            GPUname: 'NVIDIA RTX 3080 Ti',
            Hashrate: '85.41  ',
            Power: '257',
            Efficency: '0.33',
            Revenue: '2.82',
            ROI: '425',
        },
        { 
            id: 8,
            GPUname: 'NVIDIA CMP 70HX',
            Hashrate: '81.60  ',
            Power: '199',
            Efficency: '0.41',
            Revenue: '2.69',
            ROI: '519' 
        },
        { 
            id: 9,
            GPUname: 'NVIDIA RTX 3080 LHR',
            Hashrate: '71.70',
            Power: '227',
            Efficency: '0.32',
            Revenue: '2.37',
            ROI: '422' 
        },
        { 
            id: 10,
            GPUname: 'AMD BC-160',
            Hashrate: '71.00  ',
            Power: '130',
            Efficency: '0.55',
            Revenue: '2.34',
            ROI: '853' 
        },
        { 
            id: 11,
            GPUname: 'AMD RX 6800 XT',
            Hashrate: '63.20  ',
            Power: '104',
            Efficency: '0.61',
            Revenue: '2.09',
            ROI: '311' 
        },
        { 
            id: 12,
            GPUname: 'AMD RX 6900 XT',
            Hashrate: '62.91  ',
            Power: '143',
            Efficency: '0.44',
            Revenue: '2.08',
            ROI: '481' 
        },
        { 
            id: 13,
            GPUname: 'NVIDIA RTX 3060 Ti',
            Hashrate: '62.42  ',
            Power: '125',
            Efficency: '0.50',
            Revenue: '2.06',
            ROI: '194' 
        },
        { 
            id: 14,
            GPUname: 'NVIDIA RTX 3070',
            Hashrate: '62.34  ',
            Power: '115',
            Efficency: '0.54',
            Revenue: '2.06',
            ROI: '242' 
        },
        { 
            id: 15,
            GPUname: 'NVIDIA RTX A4000',
            Hashrate: '62.03  ',
            Power: '124',
            Efficency: '0.50',
            Revenue: '2.05',
            ROI: '488' 
        },
        { 
            id: 16,
            GPUname: 'AMD RX 6800',
            Hashrate: '61.01  ',
            Power: '108',
            Efficency: '0.56',
            Revenue: '2.01',
            ROI: '288' 
        },
        { id: 17,
            GPUname: 'NVIDIA RTX 3070 Ti',
Hashrate: '57.62  ',
Power: '186 ',
Efficency: '0.31  ',
Revenue: ' 1.90',
ROI: '315  ' },
        { id: 18,
            GPUname: 'NVIDIA RTX 2080 Ti',
Hashrate: '57.46  ',
Power: '160 ',
Efficency: '0.36  ',
Revenue: ' 1.90',
ROI: '685  ' },
        { id: 19,
            GPUname: 'AMD RX 5700',
Hashrate: '56.74  ',
Power: '135 ',
Efficency: '0.42  ',
Revenue: ' 1.87',
ROI: '203  ' },
        { id: 20,
            GPUname: 'AMD RX 5700 XT',
Hashrate: '56.44  ',
Power: '125 ',
Efficency: '0.45  ',
Revenue: ' 1.86',
ROI: '242  ' },
        { id: 21,
            GPUname: 'AMD VEGA 56',
Hashrate: '53.70  ',
Power: '175 ',
Efficency: '0.31  ',
Revenue: ' 1.77',
ROI: '225  ' },
        { id: 22,
            GPUname: 'AMD BC-250',
Hashrate: '50.64  ',
Power: '84 ',
Efficency: '0.60  ',
Revenue: ' 1.67',
ROI: '598  ' },
        { id: 23,
            GPUname: 'AMD VEGA 64',
Hashrate: '48.82  ',
Power: '170 ',
Efficency: '0.29  ',
Revenue: ' 1.61',
ROI: '310  ' },
        { id: 24,
            GPUname: 'AMD RX 6700 XT',
Hashrate: '46.95  ',
Power: '98 ',
Efficency: '0.48  ',
Revenue: ' 1.55',
ROI: '309  ' },
        { id: 25,
            GPUname: 'NVIDIA RTX 2080 Super',
Hashrate: '46.00  ',
 Power: '160 ',
Efficency: '0.29  ',
Revenue: ' 1.52',
ROI: '460  ' },
        { id: 26,
            GPUname: 'NVIDIA RTX 3070 LHR',
Hashrate: '45.43  ',
 Power: '107 ',
Efficency: '0.42  ',
Revenue: ' 1.50',
ROI: '333  ' },
        { id: 27,
            GPUname: 'NVIDIA RTX 2070 Super',
Hashrate: '45.32  ',
 Power: '111 ',
Efficency: '0.41  ',
Revenue: ' 1.50',
ROI: '334  ' },
        { id: 28,
            GPUname: 'NVIDIA RTX 2070',
Hashrate: '45.13  ',
 Power: '103 ',
Efficency: '0.44  ',
Revenue: ' 1.49',
ROI: '335  ' },
        { id: 29,
            GPUname: 'NVIDIA RTX 2080',
Hashrate: '45.10  ',
 Power: '116 ',
Efficency: '0.39  ',
Revenue: ' 1.49',
ROI: '537  ' },
        { id: 30,
            GPUname: 'NVIDIA RTX 3060 Ti LHR',
Hashrate: '45.05  ',
 Power: '146 ',
Efficency: '0.31  ',
Revenue: ' 1.49',
ROI: '336  ' },
        { id: 31,
            GPUname: 'NVIDIA P102-100',
Hashrate: '45.00  ',
 Power: '190 ',
Efficency: '0.24  ',
Revenue: ' 1.49',
ROI: '525  ' },
        { id: 32,
            GPUname: 'NVIDIA RTX 2060 Super',
Hashrate: '44.04  ',
 Power: '105 ',
Efficency: '0.42  ',
Revenue: ' 1.45',
ROI: '274  ' },
        { id: 33,
            GPUname: 'NVIDIA RTX A2000',
Hashrate: '43.25  ',
 Power: '67 ',
Efficency: '0.65  ',
Revenue: ' 1.43',
ROI: '455  ' },
        { id: 34,
            GPUname: 'NVIDIA GTX 1080 Ti',
Hashrate: '43.23  ',
 Power: '198 ',
Efficency: '0.22  ',
Revenue: ' 1.43',
ROI: '490  ' },
        { id: 35,
            GPUname: 'AMD RX 5600 XT',
Hashrate: '41.66  ',
 Power: '110 ',
Efficency: '0.38  ',
Revenue: ' 1.38',
ROI: '203  ' },
        { id: 36,
            GPUname: 'NVIDIA RTX 3060',
Hashrate: '40.30  ',
 Power: '113 ',
Efficency: '0.36  ',
Revenue: ' 1.33',
ROI: '247  ' },
        { id: 37,
            GPUname: 'NVIDIA P104-100',
Hashrate: '36.27  ',
 Power: '135 ',
Efficency: '0.27  ',
Revenue: ' 1.20',
ROI: '333  ' },
        { id: 38,
            GPUname: 'NVIDIA RTX 3060 LHR v2',
Hashrate: '36.08  ',
 Power: '118 ',
Efficency: '0.31  ',
Revenue: ' 1.19',
ROI: '276  ' },
        { id: 39,
            GPUname: 'NVIDIA RTX 2060',
Hashrate: '33.85  ',
 Power: '81 ',
Efficency: '0.42  ',
Revenue: ' 1.12',
ROI: '357  ' },
        { id: 40,
            GPUname: 'NVIDIA GTX 1080',
Hashrate: '33.84  ',
 Power: '135 ',
Efficency: '0.25  ',
Revenue: ' 1.12',
ROI: '537  ' },
        { id: 41,
            GPUname: 'NVIDIA RTX 2060 12GB',
Hashrate: '33.61  ',
 Power: '86 ',
Efficency: '0.39  ',
Revenue: ' 1.11',
ROI: '433  ' },
        { id: 42,
            GPUname: 'NVIDIA GTX 1070 Ti',
Hashrate: '33.46  ',
 Power: '135 ',
Efficency: '0.25  ',
Revenue: ' 1.10',
ROI: '407  ' },
        {
            id: 43,
            GPUname: 'AMD RX 570',
            Hashrate: '32.32  ',
             Power: '135 ',
            Efficency: '0.24  ',
            Revenue: ' 1.07',
            ROI: '196  ',
        },
        {
            id: 44,
            GPUname: 'AMD RX 580',
            Hashrate: '32.22  ',
             Power: '135 ',
            Efficency: '0.24  ',
            Revenue: ' 1.06',
            ROI: '215  ',
        },
        {
            id: 45,
            GPUname: 'AMD RX 6600 XT',
            Hashrate: '31.88  ',
             Power: '68 ',
            Efficency: '0.47  ',
            Revenue: ' 1.05',
            ROI: '360  ',
        },
        {
            id: 46,
            GPUname: 'NVIDIA GTX 1660 Super',
            Hashrate: '31.74  ',
             Power: '75 ',
            Efficency: '0.42  ',
            Revenue: ' 1.05',
            ROI: '219  ',
        },
        {
            id: 47,
            GPUname: 'NVIDIA GTX 1660 Ti',
            Hashrate: '31.10  ',
             Power: '60 ',
            Efficency: '0.52  ',
            Revenue: ' 1.03',
            ROI: '273  ',
        },
        {
            id: 48,
            GPUname: 'AMD RX 470',
            Hashrate: '31.00  ',
             Power: '130 ',
            Efficency: '0.24  ',
            Revenue: ' 1.02',
            ROI: '235  ',
        },
        {
            id: 49,
            GPUname: 'AMD RX 6600',
            Hashrate: '28.76  ',
             Power: '68 ',
            Efficency: '0.42  ',
            Revenue: ' 0.95',
            ROI: '347  ',
        },
        {
            id: 50,
            GPUname: 'NVIDIA GTX 1070',
            Hashrate: '28.00  ',
             Power: '120 ',
            Efficency: '0.23  ',
            Revenue: ' 0.92',
            ROI: '411  ',
        },
        {
            id: 51,
            GPUname: 'AMD RX 5500 XT',
            Hashrate: '27.24  ',
             Power: '65 ',
            Efficency: '0.42  ',
            Revenue: ' 0.90',
            ROI: '221  ',
        },
        {
            id: 52,
            GPUname: 'NVIDIA GTX 1660',
            Hashrate: '26.50  ',
             Power: '80 ',
            Efficency: '0.33  ',
            Revenue: ' 0.87',
            ROI: '250  ',
        },
        {
            id: 53,
            GPUname: 'NVIDIA P106-100',
            Hashrate: '24.04  ',
             Power: '86 ',
            Efficency: '0.28  ',
            Revenue: ' 0.79',
            ROI: '377  ',
        },
        {
            id: 54,
            GPUname: 'NVIDIA GTX 1060',
            Hashrate: '22.00  ',
             Power: '85 ',
            Efficency: '0.26  ',
            Revenue: ' 0.73',
            ROI: '344  ',
        },
        {
            id: 55,
            GPUname: 'NVIDIA RTX 3050',
            Hashrate: '16.80  ',
             Power: '67 ',
            Efficency: '0.25  ',
            Revenue: ' 0.55',
            ROI: '449  ',
        },

    ]);
    const columns = [
      {
        title: 'GPUname',
        dataIndex: 'GPUname',
        key: 'GPUname',
        filters: [
            {
              text: 'NVIDIA',
              value: 'NVIDIA',
            },
            {
              text: 'AMD',
              value: 'AMD',
            },
        ],
        onFilter: (value, record) => record.GPUname.indexOf(value) === 0,
        sorter: (a, b) => a.GPUname.length - b.GPUname.length,
        sortDirections: ['descend'],
      },
      {
        title: 'Hashrate  (Mh/s)',
        dataIndex: 'Hashrate',
        key: 'Hashrate',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.Hashrate - b.Hashrate,
      },
      
      {
        title: ' Power (W)',
        dataIndex: 'Power',
        key: 'Power',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.Power - b.Power,
      },
      {
        title: 'Efficency (Mh/W)',
        dataIndex: 'Efficency',
        key: 'Efficency',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.Efficency - b.Efficency,
      },
      {
        title: 'Revenue ( $ )',
        dataIndex: 'Revenue',
        key: 'Revenue',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.Revenue - b.Revenue,
      },
      {
        title: 'ROI ( Days )',
        dataIndex: 'ROI',
        key: 'ROI',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.ROI - b.ROI,
      },
    ];
    
    function onChange(pagination, filters, sorter, extra) {
        console.log('params', pagination, filters, sorter, extra);
      }

    return (
      <>
        <Title level={2} className="heading">ETH Hashrate</Title>
        <Table 
        columns={columns} 
        dataSource={ETH_Hashrate} 
        onChange={onChange} 
        title={() => 'Those are informations only for ETH Coin.'}
        footer={() => 'Those informations are indicative, things like performance, for example, may change in reality. So, don\'t take everything for truth.'}/>
      </>
    );
}
